name: polycheck
version: 0.1.0.0
github: "AliaumeL/polyregular-model-checking"
license: GPL-3.0
author: "Aliaume Lopez and Rafał Stefański"
maintainer: "ad.lopez@uw.edu.pl"
copyright: "2025 Aliaume Lopez and Rafał Stefański"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/AliaumeL/polyregular-model-checking>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - process
  - directory
  - extra
  - mtl
  - text
  - array
  - temporary
  - scotty
  - aeson
  - filepath

build-tools:
  - alex
  - happy

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  #- -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src

executables:
  polycheck:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - polycheck
      - optparse-applicative
  benchmarker:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - polycheck
      - optparse-applicative
tests:
  polycheck-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - polycheck
      - hspec
      - QuickCheck
