-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language SimpleForProgram.

module Parser.SimpleForProgram.Abs where

import Prelude (Char, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Program VarStmt
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarStmt = VarStmt [IdentHash] [Stmt] | NoVarStmt [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FORInput = FInput | FRevInput
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
    = SFor IdentHash FORInput VarStmt
    | SSetTrue IdentHash
    | SIfElse BExpr [Stmt] [Stmt]
    | SIf BExpr [Stmt]
    | SPrintChar Char
    | SPrintLabel IdentHash
    | SSkip
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BExpr
    = BTrue
    | BFalse
    | BVar IdentHash
    | BNot BExpr
    | BTest IdentHash BTest IdentHash
    | BLabelAt IdentHash Char
    | BAnd BExpr BExpr
    | BOr BExpr BExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BTest = TLe | TLt | TGe | TGt | TEq | TNeq
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype IdentHash = IdentHash String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

