-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Parser.

module Parser.SimpleForProgram.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Parser.SimpleForProgram.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Parser.SimpleForProgram.Abs.IdentHash where
  prt _ (Parser.SimpleForProgram.Abs.IdentHash i) = doc $ showString i
instance Print [Parser.SimpleForProgram.Abs.Stmt] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Parser.SimpleForProgram.Abs.IdentHash] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.SimpleForProgram.Abs.Program where
  prt i = \case
    Parser.SimpleForProgram.Abs.Program varstmt -> prPrec i 0 (concatD [prt 0 varstmt])

instance Print Parser.SimpleForProgram.Abs.VarStmt where
  prt i = \case
    Parser.SimpleForProgram.Abs.VarStmt identhashs stmts -> prPrec i 0 (concatD [doc (showString "let"), prt 0 identhashs, doc (showString ":="), doc (showString "false"), doc (showString "in"), prt 0 stmts])
    Parser.SimpleForProgram.Abs.NoVarStmt stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print Parser.SimpleForProgram.Abs.FORInput where
  prt i = \case
    Parser.SimpleForProgram.Abs.FInput -> prPrec i 0 (concatD [doc (showString "input")])
    Parser.SimpleForProgram.Abs.FRevInput -> prPrec i 0 (concatD [doc (showString "reversed"), doc (showString "("), doc (showString "input"), doc (showString ")")])

instance Print Parser.SimpleForProgram.Abs.Stmt where
  prt i = \case
    Parser.SimpleForProgram.Abs.SFor identhash forinput varstmt -> prPrec i 0 (concatD [doc (showString "for"), prt 0 identhash, doc (showString "in"), prt 0 forinput, doc (showString "do"), prt 0 varstmt, doc (showString "done")])
    Parser.SimpleForProgram.Abs.SSetTrue identhash -> prPrec i 0 (concatD [prt 0 identhash, doc (showString ":="), doc (showString "true")])
    Parser.SimpleForProgram.Abs.SIfElse bexpr stmts1 stmts2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 bexpr, doc (showString "then"), prt 0 stmts1, doc (showString "else"), prt 0 stmts2, doc (showString "endif")])
    Parser.SimpleForProgram.Abs.SIf bexpr stmts -> prPrec i 0 (concatD [doc (showString "if"), prt 0 bexpr, doc (showString "then"), prt 0 stmts, doc (showString "endif")])
    Parser.SimpleForProgram.Abs.SPrintChar c -> prPrec i 0 (concatD [doc (showString "print"), prt 0 c])
    Parser.SimpleForProgram.Abs.SPrintLabel identhash -> prPrec i 0 (concatD [doc (showString "print"), prt 0 identhash])
    Parser.SimpleForProgram.Abs.SSkip -> prPrec i 0 (concatD [doc (showString "skip")])

instance Print Parser.SimpleForProgram.Abs.BExpr where
  prt i = \case
    Parser.SimpleForProgram.Abs.BTrue -> prPrec i 2 (concatD [doc (showString "true")])
    Parser.SimpleForProgram.Abs.BFalse -> prPrec i 2 (concatD [doc (showString "false")])
    Parser.SimpleForProgram.Abs.BVar identhash -> prPrec i 2 (concatD [prt 0 identhash])
    Parser.SimpleForProgram.Abs.BNot bexpr -> prPrec i 2 (concatD [doc (showString "not"), prt 2 bexpr])
    Parser.SimpleForProgram.Abs.BTest identhash1 btest identhash2 -> prPrec i 2 (concatD [prt 0 identhash1, prt 0 btest, prt 0 identhash2])
    Parser.SimpleForProgram.Abs.BLabelAt identhash c -> prPrec i 2 (concatD [doc (showString "label"), doc (showString "("), prt 0 identhash, doc (showString ")"), doc (showString "=="), prt 0 c])
    Parser.SimpleForProgram.Abs.BAnd bexpr1 bexpr2 -> prPrec i 1 (concatD [prt 2 bexpr1, doc (showString "and"), prt 1 bexpr2])
    Parser.SimpleForProgram.Abs.BOr bexpr1 bexpr2 -> prPrec i 0 (concatD [prt 1 bexpr1, doc (showString "or"), prt 0 bexpr2])

instance Print Parser.SimpleForProgram.Abs.BTest where
  prt i = \case
    Parser.SimpleForProgram.Abs.TLe -> prPrec i 0 (concatD [doc (showString "<=")])
    Parser.SimpleForProgram.Abs.TLt -> prPrec i 0 (concatD [doc (showString "<")])
    Parser.SimpleForProgram.Abs.TGe -> prPrec i 0 (concatD [doc (showString ">=")])
    Parser.SimpleForProgram.Abs.TGt -> prPrec i 0 (concatD [doc (showString ">")])
    Parser.SimpleForProgram.Abs.TEq -> prPrec i 0 (concatD [doc (showString "==")])
    Parser.SimpleForProgram.Abs.TNeq -> prPrec i 0 (concatD [doc (showString "!=")])
