name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aliaume/polycheck:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd polyreg
          stack build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: |
          cd polyreg
          stack build --enable-tests --enable-benchmarks all
      - name: Run tests
        run: |
          cd polyreg
          stack test all
