name: haskell and latex CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install texlive-full
        run: sudo apt-get install -y texlive-full
      - name: Build
        run: |
          cd paper
          make all
      - name: Upload pdfs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: polycheck.pdf
          path: paper/polycheck.pdf

  build:
    runs-on: ubuntu-latest
    container:
      image: aliaume/polycheck:latest
    steps:
      # https://github.com/commercialhaskell/stack/issues/2187
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Check out code
        run: |
          git clone https://github.com/AliaumeL/polyregular-model-checking.git
      - name: Build
        run: |
          cd polyregular-model-checking/polycheck
          # --nix to use nix dependencies
          # --allow-different-user because github changes the user
          stack init --nix --nix-packages "zlib" --allow-different-user
          stack build --nix --nix-packages "zlib" --allow-different-user
      - name: Run test suite
        run: |
          cd polyregular-model-checking/polycheck
          # disable test suite for the moment because it is too long
          # stack test --nix --nix-packages "zlib"  --allow-different-user
