name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aliaume/polycheck:latest
    steps:
      # https://github.com/commercialhaskell/stack/issues/2187
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Check out code
        run: |  
          git clone https://github.com/AliaumeL/polyregular-model-checking.git
      - name: Install dependencies
        run: |
          cd polyregular-model-checking/polyreg
          stack build --only-dependencies 
      - name: Build
        run: |
          cd polyregular-model-checking/polyreg
          stack build
      - name: Run tests
        run: |
          cd polyregular-model-checking/polyreg
          stack test all
