name: Release

on:
  push:
    tags:
      - "v.*.*.*"
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Docker Image
        run: |
          nix-build ./polycheck.nix -A polycheck-img
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: |
          nix-build ./polycheck.nix -A polycheck-img
          docker load < result
          docker push aliaume/polycheck-small:latest
  github:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    name: Polycheck - Release - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell-actions/setup@v2.7.9
        with:
          stack-version: "latest"
          enable-stack: true
      - name: Build release assets
        run: |
          cd polycheck
          stack init
          stack setup
          stack build --copy-bins --ghc-options="-O2"
      - name: Package binaries
        run: |
          cd polycheck
          # create the temporary directory
          mkdir -p artifacts/${{ matrix.os }}
          # copy binary files
          cp $(stack path --local-install-root)/bin/* artifacts/${{ matrix.os }}/
          # copy assets
          cp -R assets/ artifacts/${{ matrix.os }}/assets/
          # zip the assets/ directory into a file in the tar.gz format
          tar -czf polycheck-${{ matrix.target }}.tar.gz -C artifacts/${{ matrix.os }} .
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          files: "polycheck/*.tar.gz"
      - name: Upload Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          path: "polycheck/*.tar.gz"
